[tool.poetry]
name = "stark-llm-playground"
version = "0.1.0"
description = "Experimental LLM and embeddings-based processors for STARK"
authors = ["Mark Parker <mark@parker-programs.com>"]
license = "CC BY-NC-SA 4.0"
readme = "README.md"
packages = [
    { include = "ready" },
]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
stark-engine = {path = "../../../STARK", develop = true}
pydantic-ai = "^1.70.0"
# pydantic-graph = "^1.70.0"
numpy = "^2.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.1"
pytest-repeat = "^0.9.1"
pytest-timeout = "^2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
anyio_mode = "auto"
pythonpath = ["tests"]
timeout = 360
# log_cli = true
# log_cli_level = "DEBUG"
loggers = "ready" # llm playground package
filterwarnings = ["once"]
addopts = "-m 'not benchmark'"
markers = [
    "benchmark: tests that require a real model running (run with: pytest -m benchmark)",
]
